[package]
name = "ziprs"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = { version = "2.1", features = [] }
walkdir = "2.5.0"

[profile.release]
overflow-checks = true
panic = "abort"
debug = true