[package]
name = "slint"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"

i-slint-compiler = { git = "https://github.com/slint-ui/slint.git" }
spin_on = { version = "0.1.1" }

[profile.release]
overflow-checks = true
panic = "abort"
debug = true