[general]
loop_number = 5000 # How much creating/removing/checking steps will be executed
broken_files_for_each_file = 1# Number of broken files that will be created for each 1 valid file
minimize_output = true # Tries to remove some lines from output file, remember, that not always minimized file will produce same error - usually minimize output 2-100 times
temp_possible_broken_files_dir = "/opt/POSSIBLY_BROKEN_FILES_DIR" # Place where possibly broken files are saved
minimization_attempts = 500 # Attemps to minimize code, counter reset when found minimized test case
minimization_repeat = true # Repeat minimization process if smaller file was found
minimization_time = 1800
minimization_attempts_with_signal_timeout = 10 # Usually signal is sended by OOM killer or timeout which is slow to reproduce and minimize, so use it less amount than normal
debug_print_results = false # Debug prints output of commands
debug_executed_commands = false # Debug prints executed commands
debug_print_broken_files_creator = false # Debug prints results of command that created broken files
remove_non_crashing_items_from_broken_files = false # Special mode to remove non crashing files from broken files - useful if some of files were fixed in new version of app
check_for_stability = false # Check if output is stable - only able to set if stability_mode is not none
stability_runs = 3 # How many times output will be checked for stability
temp_folder = "TMP_FOLDER_TO_REPLACE" # Temp file used to store random data
timeout_group = 150
timeout = 40 # timeout time, if equal zero, then timeout is disabled
allowed_signal_statuses = ""
allowed_error_statuses = "0,1,2,101,124" # Treat file as broken if exit code is different than 0 or 1 (this is sometimes )
max_file_size_limit = 5000000
max_collected_files = 1000000000 # Max number of files that will be collected from valid_input_files_dir
ignore_file_if_contains_searched_items = true
check_if_file_is_parsable = false #true # If true, will check if file is parsable, if not, then will be removed
grouping = 100 # How many files will be grouped in one command - using bigger number than 1 will add additional step, with checking multiple files in one command
custom_folder_path = "/opt/CUSTOM" # Folder to which all broken things can be saved - it is ignored from other steps

current_mode = "custom"

[custom]
name = "boa"
command = "boa|FILE_PATHS_TO_PROVIDE"

extensions = "ts,js,mjs,mts" #,vue,svelte" # TODO - re-enable vue and svelte
valid_input_files_dir = "/opt/VALID_FILES_DIR"
broken_files_dir = "/opt/BROKEN_FILES_DIR"
group_mode = "by_group" # available: none, by_files, by_group

search_item_1 = "RUST_BACKTRACE"
search_item_2 = "panicked at"
search_item_100 = "AddressSanitizer"
search_item_101 = "LeakSanitizer"
search_item_102 = "ThreadSanitizer"
search_item_103 = "timeout: sending signal"
ignored_item_1 = "stack-overflow" # https://github.com/boa-dev/boa/issues/1402, https://github.com/boa-dev/boa/issues/4397
ignored_item_2 = "stack overflow" # https://github.com/boa-dev/boa/issues/1402, https://github.com/boa-dev/boa/issues/4397
ignored_item_3 = "is_strictly_before" # https://github.com/boa-dev/boa/issues/4398
ignored_item_4 = "a span cannot start after its end" # https://github.com/boa-dev/boa/issues/4403
ignored_item_5 = "core/parser/src/parser/expression/unary.rs" # https://github.com/boa-dev/boa/issues/4403
ignored_item_6 = "src/emit.rs" # https://github.com/boa-dev/boa/issues/4402
ignored_item_7 = "core/engine/src/vm/opcode/get/name.rs" # https://github.com/boa-dev/boa/issues/4401
ignored_item_8 = "core/engine/src/vm/opcode/define/mod.rs" # https://github.com/boa-dev/boa/issues/4400
ignored_item_9 = "core/engine/src/builtins/regexp/mod.rs" #  https://github.com/boa-dev/boa/issues/4399

file_type = "js" # Available: text, binary, js, go, rust, lua, python, slint, jsvuesvelte, svg
stability_mode = "output_content" # Available "none", "console_output", "file_content", "output_content"

