[general]
loop_number = 5000 # How much creating/removing/checking steps will be executed
broken_files_for_each_file = 2# Number of broken files that will be created for each 1 valid file
minimize_output = true # Tries to remove some lines from output file, remember, that not always minimized file will produce same error - usually minimize output 2-100 times
temp_possible_broken_files_dir = "/opt/POSSIBLY_BROKEN_FILES_DIR" # Place where possibly broken files are saved
minimization_attempts = 1000 # Attemps to minimize code, counter reset when found minimized test case
minimization_repeat = true # Repeat minimization process if smaller file was found
minimization_time = 1800
minimization_attempts_with_signal_timeout = 10 # Usually signal is sended by OOM killer or timeout which is slow to reproduce and minimize, so use it less amount than normal
debug_print_results = false # Debug prints output of commands
debug_executed_commands = false # Debug prints executed commands
debug_print_broken_files_creator = false # Debug prints results of command that created broken files
remove_non_crashing_items_from_broken_files = false # Special mode to remove non crashing files from broken files - useful if some of files were fixed in new version of app
check_for_stability = false # Check if output is stable - only able to set if stability_mode is not none
stability_runs = 3 # How many times output will be checked for stability
temp_folder = "TMP_FOLDER_TO_REPLACE" # Temp file used to store random data
timeout_group = 400
timeout = 100 # timeout time, if equal zero, then timeout is disabled
allowed_signal_statuses = ""
allowed_error_statuses = "0,1,2,101,15" # Treat file as broken if exit code is different than 0 or 1 // TODO 15 should be removed
max_file_size_limit = 5000000
max_collected_files = 1000000000 # Max number of files that will be collected from valid_input_files_dir
ignore_file_if_contains_searched_items = true
check_if_file_is_parsable = false #true # If true, will check if file is parsable, if not, then will be removed
grouping = 100 # How many files will be grouped in one command - using bigger number than 1 will add additional step, with checking multiple files in one command
custom_folder_path = "/opt/CUSTOM" # Folder to which all broken things can be saved - it is ignored from other steps

current_mode = "custom"

[custom]
name = "resvg"
command = "resvg|FILE_PATHS_TO_PROVIDE"

extensions = "svg"
valid_input_files_dir = "/opt/VALID_FILES_DIR"
broken_files_dir = "/opt/BROKEN_FILES_DIR"
group_mode = "none" # available: none, by_files, by_group

search_item_1 = "RUST_BACKTRACE"
search_item_2 = "panicked at"
search_item_100 = "AddressSanitizer"
search_item_101 = "LeakSanitizer"
search_item_102 = "ThreadSanitizer"
search_item_103 = "timeout: sending signal"
ignored_item_1 = "memory allocation of" # https://github.com/linebender/resvg/issues/852
ignored_item_2 = "requested allocation size" #  https://github.com/linebender/resvg/issues/852
ignored_item_3 = "out of memory" # https://github.com/linebender/resvg/issues/852
ignored_item_4 = "edges[curr_idx].last_y" # https://github.com/linebender/resvg/issues/933
ignored_item_5 = "src1.height == dest.height" # https://github.com/linebender/resvg/issues/934
ignored_item_55 = " == dest.height" # https://github.com/linebender/resvg/issues/934
ignored_item_556 = " == dest.width" # https://github.com/linebender/resvg/issues/934
ignored_item_6 = "val.is_finite" # https://github.com/linebender/resvg/issues/935
ignored_item_111 = ".is_finite" # https://github.com/linebender/resvg/issues/935
ignored_item_7 = "attempt to add with overflow" # https://github.com/linebender/resvg/issues/936
ignored_item_8 = "attempt to multiply with overflow" # https://github.com/linebender/resvg/issues/937
ignored_item_9 = "alpha_runs.rs:189:51" # https://github.com/linebender/resvg/issues/940
ignored_item_95 = "alpha_runs.rs:170:51" # https://github.com/linebender/resvg/issues/940
ignored_item_10 = "resvg/src/lib.rs:46:6" # https://github.com/linebender/resvg/issues/941
file_type = "svg" # Available: text, binary, js, go, rust, lua, python, slint, jsvuesvelte, svg
stability_mode = "output_content" # Available "none", "console_output", "file_content", "output_content"

