[general]
loop_number = 5000 # How much creating/removing/checking steps will be executed
broken_files_for_each_file = 20# Number of broken files that will be created for each 1 valid file
minimize_output = true # Tries to remove some lines from output file, remember, that not always minimized file will produce same error - usually minimize output 2-100 times
temp_possible_broken_files_dir = "/opt/POSSIBLY_BROKEN_FILES_DIR" # Place where possibly broken files are saved
minimization_attempts = 5000 # Attemps to minimize code, counter reset when found minimized test case
minimization_repeat = true # Repeat minimization process if smaller file was found
minimization_time = 1800
minimization_attempts_with_signal_timeout = 10 # Usually signal is sended by OOM killer or timeout which is slow to reproduce and minimize, so use it less amount than normal
debug_print_results = false # Debug prints output of commands
debug_executed_commands = false # Debug prints executed commands
debug_print_broken_files_creator = false # Debug prints results of command that created broken files
remove_non_crashing_items_from_broken_files = false # Special mode to remove non crashing files from broken files - useful if some of files were fixed in new version of app
check_for_stability = false # Check if output is stable - only able to set if stability_mode is not none
stability_runs = 3 # How many times output will be checked for stability
temp_folder = "TMP_FOLDER_TO_REPLACE" # Temp file used to store random data
timeout_group = 400
timeout = 300 # timeout time, if equal zero, then timeout is disabled
allowed_signal_statuses = "6,15" # TODO - add 15 as sometimes OS kills app with this signal
allowed_error_statuses = "0,1,2,101,124" # TODO timeout # Treat file as broken if exit code is different than 0 or 1
max_file_size_limit = 5000000
max_collected_files = 1000000000 # Max number of files that will be collected from valid_input_files_dir
ignore_file_if_contains_searched_items = true
check_if_file_is_parsable = false #true # If true, will check if file is parsable, if not, then will be removed
grouping = 100 # How many files will be grouped in one command - using bigger number than 1 will add additional step, with checking multiple files in one command
custom_folder_path = "/opt/CUSTOM" # Folder to which all broken things can be saved - it is ignored from other steps

current_mode = "custom"

[custom]
name = "rawler"
command = "rawler|FILE_PATHS_TO_PROVIDE"

extensions = "dng,orf,nrw,rw2,raf,arw,cr2,cr3,crw,nef,pef,kdc,sr2,srf,x3f,erf,orf,raw,dcr,dng,tiff"
valid_input_files_dir = "/opt/VALID_FILES_DIR"
broken_files_dir = "/opt/BROKEN_FILES_DIR"
group_mode = "none" # available: none, by_files, by_group

search_item_1 = "RUST_BACKTRACE"
search_item_2 = "panicked at"
search_item_100 = "AddressSanitizer"
search_item_101 = "LeakSanitizer"
search_item_102 = "ThreadSanitizer"
search_item_103 = "timeout: sending signal"
ignored_item_1 = "memory allocation of" # https://github.com/dnglab/dnglab/issues/570
ignored_item_2 = "requested allocation size" #  https://github.com/dnglab/dnglab/issues/570
ignored_item_3 = "out of memory" # https://github.com/dnglab/dnglab/issues/570
ignored_item_4 = "rawler/src/formats/tiff/ifd.rs" # https://github.com/dnglab/dnglab/issues/569
ignored_item_5 = "src/bits.rs" # https://github.com/dnglab/dnglab/issues/571
ignored_item_7 = "rawler/src/decoders/arw.rs" # https://github.com/dnglab/dnglab/issues/574
ignored_item_8 = "assertion failed: p1.y <= p2.y" # https://github.com/dnglab/dnglab/issues/573
ignored_item_9 = "p1.x <= p2.x" # https://github.com/dnglab/dnglab/issues/573
ignored_item_11 = "v4decompressor.rs" # https://github.com/dnglab/dnglab/issues/571
ignored_item_23 = "src/imgop/mod.rs" # https://github.com/dnglab/dnglab/issues/582
ignored_item_24 = "Lensdata version" # https://github.com/dnglab/dnglab/issues/583
ignored_item_25 = "Unknown CFA size" # https://github.com/dnglab/dnglab/issues/586
ignored_item_29 = "src/pumps.rs" # https://github.com/dnglab/dnglab/issues/587
ignored_item_26 = "attempt to multiply with overflow" # TODO
ignored_item_27 = "fuji_decompressor.rs" # TODO - generated files are too big, and cannot be really minimized
ignored_item_30 = "decompressors/crx/mod.rs" # TODO - generated files are too big, and cannot be really minimized
ignored_item_31 = "decompressors/ljpeg/mod.rs" # TODO - generated files are too big, and cannot be really minimized
ignored_item_32 = "decompressors/ljpeg/huffman.rs" # TODO - generated files are too big, and cannot be really minimized

file_type = "binary" # Available: text, binary, js, go, rust, lua, python, slint, jsvuesvelte, svg, gdscript
stability_mode = "output_content" # Available "none", "console_output", "file_content", "output_content"

