[package]
name = "rawler"
version = "0.1.0"
edition = "2021"

[dependencies]
rawler = { git = "https://github.com/dnglab/dnglab.git" }
walkdir = "2.5.0"
image = { version = "0.25.6", features = ["jpeg"], default-features = false }

[profile.release]
overflow-checks = true
panic = "abort"
debug = true
debug-assertions = true