[package]
name = "zip_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = { git = "https://github.com/zip-rs/zip2.git" }
walkdir = "2.5.0"

[profile.release]
overflow-checks = true
panic = "abort"
debug = true
debug-assertions = true