[package]
name = "lopdf"
version = "0.1.0"
edition = "2021"

[dependencies]
lopdf = { git = "https://github.com/J-F-Liu/lopdf.git" }
walkdir = "2.5.0"

[profile.release]
overflow-checks = true
panic = "abort"
debug = true
debug-assertions = true