[package]
name = "lofty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lofty = { git = "https://github.com/Serial-ATA/lofty-rs/" }
walkdir = "2.5.0"


[profile.release]
overflow-checks = true
panic = "abort"
debug = true
debug-assertions = true