name: 🐧 AFL Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 21 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  afl-ci:

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: LOFTY
            fuzz_target: lofty
            timeout: 18000
            files: "AA_MUSIC_VALID_FILES.7z"
          - name: DICOM
            fuzz_target: dicom
            timeout: 18000
            files: "AA_DCM_VALID_FILES.7z"
          - name: FONT_KIT
            fuzz_target: font_kit
            timeout: 18000
            files: "AA_FONT_VALID_FILES_MORE.7z"
          - name: ZIP_RS
            fuzz_target: zip_rs
            timeout: 18000
            files: "AA_ZIP_VALID_FILES.7z"

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust version
        run: |
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget earlyoom libasan8

      - name: Install create_broken_files and sd
        run: cargo install create_broken_files sd cargo-fuzz

      - name: Build
        run: cargo build --release

      - name: Download and prepare data files
        run: |
          CURR_DIR=$(pwd)
          mkdir -p /opt/INPUT_FILES_DIR
          cd /opt/INPUT_FILES_DIR
          
          python3 "$CURR_DIR/download_helper.py" "${{ matrix.files }}"
          
          cd $CURR_DIR

      - name: Configure fuzzer
        run: |
          cd fuzz
          cargo update
          cd ../

      - name: Run Fuzzer
        run: |
          RUSTFLAGS="-Zsanitizer=address" cargo fuzz run ${{ matrix.fuzz_target }} /opt/INPUT_FILES_DIR/ -- -max_len=99999 -max_total_time=${{ matrix.timeout }}

      - name: Store fuzz results after
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: CARGO_FUZZ___${{ matrix.name }}
          path: fuzz/artifacts