name: 🐧 Cargo Fuzz Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 21 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-check-ci:

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: LOFTY
            fuzz_target: lofty
            timeout: 6000
            files: "AA_MUSIC_VALID_FILES.7z"
          - name: DICOM
            fuzz_target: dicom
            timeout: 6000
            files: "AA_DCM_VALID_FILES.7z"
          #          - name: FONT_KIT # https://github.com/servo/font-kit/issues/250
          #            fuzz_target: font_kit
          #            timeout: 6000
          #            files: "AA_FONT_VALID_FILES_MORE.7z"
          #          - name: FULL_MOON
          #            fuzz_target: full_moon
          #            timeout: 6000
          #            files: "AA_LUA_VALID_FILES.7z"
          - name: IMAGE
            fuzz_target: image
            timeout: 6000
            files: "AA_IMAGE_VALID_FILES.7z"
          #          - name: LOPDF # Stack overflow
          #            fuzz_target: lopdf
          #            timeout: 6000
          #            files: "AA_PDF_VALID_FILES.7z"
          #          - name: PDF_RS # TODO - not implemented - not know how to load from memory
          #            fuzz_target: pdf_rs
          #            timeout: 6000
          #            files: "AA_PDF_VALID_FILES.7z"
          - name: RSBUZZ
            fuzz_target: rsbuzz
            timeout: 6000
            files: "AA_FONT_VALID_FILES_MORE.7z"
          #          - name: SYMPHONIA
          #            fuzz_target: symphonia
          #            timeout: 6000
          #            files: "AA_MUSIC_VALID_FILES.7z"
          - name: ZIP_RS
            fuzz_target: zip_rs
            timeout: 6000
            files: "AA_ZIP_VALID_FILES.7z"

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust version
        run: |
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget earlyoom libasan8
          sudo apt install -y pkg-config libfreetype6-dev libfontconfig1-dev # For font_kit

      - name: Install cargo fuzz
        run: cargo install cargo-fuzz

      - name: Download and prepare data files
        run: |
          CURR_DIR=$(pwd)
          mkdir -p /opt/INPUT_FILES_DIR
          cd /opt/INPUT_FILES_DIR
          
          python3 "$CURR_DIR/download_helper.py" "${{ matrix.files }}"
          
          cd $CURR_DIR

      - name: Configure fuzzer
        run: |
          cd fuzz
          cargo update
          cd ../

      - name: Build Fuzzer
        run: |
          cd fuzz
          export RUST_BACKTRACE=1
          export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-18)
          export ASAN_OPTIONS=symbolize=1
          RUSTFLAGS="-Zsanitizer=address" cargo fuzz build ${{ matrix.fuzz_target }} --release --features "${{ matrix.fuzz_target }}_f"
          cd ../

      - name: Run Fuzzer
        run: |
          export RUST_BACKTRACE=1
          export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-18)
          export ASAN_OPTIONS="symbolize=1:allocator_may_return_null=1"
          export RUSTFLAGS="-Zsanitizer=address"
          cargo fuzz run ${{ matrix.fuzz_target }} /opt/INPUT_FILES_DIR/ --release --features "${{ matrix.fuzz_target }}_f" -- -max_len=99999 -max_total_time=${{ matrix.timeout }} -rss_limit_mb=20000 || true

      - name: Store fuzz results before minimization
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: CARGO_FUZZ___${{ matrix.name }}___before
          path: fuzz/artifacts

      - name: Minimalize fuzz results
        run: |
          export RUST_BACKTRACE=1
          export ASAN_SYMBOLIZER_PATH=$(which llvm-symbolizer-18)
          export ASAN_OPTIONS="symbolize=1:allocator_may_return_null=1"
          export RUSTFLAGS="-Zsanitizer=address"
          
          for file in fuzz/artifacts/*; do cargo fuzz tmin "${{ matrix.fuzz_target }}" "$file" --release --features "${{ matrix.fuzz_target }}_f" -- -rss_limit_mb=20000 || true; done

      - name: Store fuzz results after minimization
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: CARGO_FUZZ___${{ matrix.name }}___after
          path: fuzz/artifacts

      - name: Exit when found broken files
        run: |
          [ "$(ls -A fuzz/artifacts/${{ matrix.fuzz_target }})" ] && exit 1 || true
