name: Common Step Before

on: [ workflow_call ]

jobs:
  common-steps:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup rust version
        run: |
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add llvm-tools-preview --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget earlyoom libasan8

      - name: Install create_broken_files and sd
        run: cargo install create_broken_files sd